spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeemanager?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  data:
    redis:
      port: 6379
      host: localhost
      database: 0
server:
  port: 80

mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
